///*****************************************
//  Copyright (C) 2009-2014
//  ITE Tech. Inc. All Rights Reserved
//  Proprietary and Confidential
///*****************************************
//   @file   <515XRAM.H>
//   @author Max.Kao@ite.com.tw
//   @date   2014/09/11
//   @fileversion: ITE_MHLRX_SAMPLE_V1.01
//******************************************/

#ifndef _IT6602_515xram_
#define _IT6602_515xram_
/*
#define MySon
#ifdef MySon
extern // xdata  PADMOD0        _at_  0x0f50;

extern // xdata  PORT4OE        _at_  0x0f57;
#else

#endif
*/
#endif
