#ifndef GSV2K2_RXAUD_MAP_FCT_H
#define GSV2K2_RXAUD_MAP_FCT_H
#define GSV2K2_RXAUD_set_RX_DSD_OUT_MAN_SEL(port, val)                  AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x01, 0x10, 0x4, val)
#define GSV2K2_RXAUD_set_RX_DSD_OUT_MAN_EN(port, val)                   AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x01, 0x8, 0x3, val)
#define GSV2K2_RXAUD_set_RX_HBR_OUT_MAN_EN(port, val)                   AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x01, 0x4, 0x2, val)
#define GSV2K2_RXAUD_set_RX_HBR_OUT_MAN_SEL(port, val)                  AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x01, 0x2, 0x1, val)
#define GSV2K2_RXAUD_set_RX_DIS_I2S_ZERO_COMPR(port, val)               AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x03, 0x80, 0x7, val)
#define GSV2K2_RXAUD_get_RX_AUDIO_PLL_LOCKED(port, pval)                AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x04, 0x1, 0x0, pval)
#define GSV2K2_RXAUD_get_ACR_PKT_DET(port, pval)                        AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x18, 0x80, 0x7, pval)
#define GSV2K2_RXAUD_get_AUD_IF_PKT_DET(port, pval)                     AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x19, 0x80, 0x7, pval)
#define GSV2K2_RXAUD_get_HBR_AUDIO_PKT_DET(port, pval)                  AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x19, 0x20, 0x5, pval)
#define GSV2K2_RXAUD_get_DST_AUDIO_PKT_DET(port, pval)                  AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x19, 0x10, 0x4, pval)
#define GSV2K2_RXAUD_get_DSD_AUDIO_PKT_DET(port, pval)                  AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x19, 0x8, 0x3, pval)
#define GSV2K2_RXAUD_get_AUDIO_SAMPLE_PKT_DET(port, pval)               AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x19, 0x4, 0x2, pval)
#define GSV2K2_RXAUD_set_DISABLE_AUDIO_MUTE(port, val)                  AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x3F, 0x20, 0x5, val)
#define GSV2K2_RXAUD_set_RX_AUD_FIFO_RST(port, val)                     AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x48, 0x80, 0x7, val)
#define GSV2K2_RXAUD_set_CLEAR_AUDIO_HB_CONTENT(port, val)              AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x5A, 0x4, 0x2, val)
#define GSV2K2_RXAUD_set_RX_PKT_DET_RST(port, val)                      AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x5A, 0x2, 0x1, val)
#define GSV2K2_RXAUD_get_MAN_TDM_ENABLE(port, pval)                     AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x62, 0x80, 0x7, pval)
#define GSV2K2_RXAUD_set_MAN_TDM_ENABLE(port, val)                      AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x62, 0x80, 0x7, val)
#define GSV2K2_RXAUD_get_RX_SEL_I2S(port, pval)                         AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x64, 0x40, 0x6, pval)
#define GSV2K2_RXAUD_set_RX_SEL_I2S(port, val)                          AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x64, 0x40, 0x6, val)
#define GSV2K2_RXAUD_get_CSDATA_VALID(port, pval)                       AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x65, 0x80, 0x7, pval)
#define GSV2K2_RXAUD_get_NUM_CH(port, pval)                             AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x65, 0x3F, 0, pval)
#define GSV2K2_RXAUD_get_RB_RX_VIDEO_3D_FIELD_ALT(port, pval)           AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x81, 0x2, 0x1, pval)
#define GSV2K2_RXAUD_get_RB_RX_VIDEO_3D(port, pval)                     AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x81, 0x1, 0x0, pval)
#define GSV2K2_RXAUD_get_RX_AUDIO_PIN_NUM(port, pval)                   AvHalI2cReadField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x87, 0x18, 3, pval)
#define GSV2K2_RXAUD_set_RX_AUDIO_PIN_NUM(port, val)                    AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x87, 0x18, 3, val)
#define GSV2K2_RXAUD_set_WORD_LEN_MAN_EN(port, val)                     AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x8A, 0x40, 0x6, val)
#define GSV2K2_RXAUD_set_WORD_LEN_MAN(port, val)                        AvHalI2cWriteField8(GSV2K2_RXAUD_MAP_ADDR(port), 0x8A, 0x3F, 0, val)
#endif
