/**
******************************************************************************
* @file    ms7200_drv_hdmi_rx_config.h
* @author  
* @version V1.0.0
* @date    20-Nov-2017
* @brief   hdmi_rx module configurations.
* @history 
*
* Copyright (c) 2009-2014, MacroSilicon Technology Co.,Ltd.
******************************************************************************/
#ifndef __MACROSILICON_MS7200_DRV_HDMI_RX_CONFIG_H__
#define __MACROSILICON_MS7200_DRV_HDMI_RX_CONFIG_H__

#define REG_MISC_CLK_CTRL0                                 (0x03)
#define REG_MISC_CLK_CTRL1                                 (0x04)
#define REG_MISC_RST_CTRL0                                 (0x09)
#define REG_MISC_RST_CTRL1                                 (0x0A)
#define REG_MISC_RX_PHY_SEL                                (0x0C)
#define REG_MISC_5V_DET                                    (0x15)
#define REG_MISC_INT_PIN_CTRL                              (0x18)

#define REG_MISC_AV_CTRL2                                  (0x23)

//top misc mdt
#define REG_MISC_MD_HSW_L                                  (0x36)
#define REG_MISC_MD_HSW_H                                  (0x37)
//
#define REG_MISC_MD_VSW_L                                  (0x3E)
#define REG_MISC_MD_VSW_H                                  (0x3F)
#define REG_MISC_MD_VBACK_L                                (0x40)
#define REG_MISC_MD_VBACK_H                                (0x41)

//audio ctrl
#define REG_MISC_AUD_CTRL                                  (0x48)
#define REG_MISC_C_BYTE0                                   (0x50)
#define REG_MISC_C_BYTE2                                   (0x52)
#define REG_MISC_C_BYTE3                                   (0x53)
#define REG_MISC_C_BYTE4                                   (0x54)

//rc ctrl
#define REG_MISC_RC_CTRL1                                  (0x60)
#define REG_MISC_RC_CTRL2                                  (0x61)

//IO ctrl1
#define REG_MISC_IO_CTRL1                                  (0x77)

/* hdmi rx phy register address map */
#define MS7200_HDMI_RX_PI_RXRCV_REG_BASE            (0x0200)

#define REG_PI_CDR_RST                              (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x00)
#define REG_PI_CDR_CODE0                            (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x01)
#define REG_PI_CDR_CODE1                            (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x02)
#define REG_PI_CDR_CODE2                            (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x03)
#define REG_PI_CTRL0                                (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x04)
#define REG_PI_CTRL1                                (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x05)
#define REG_PI_CODE_RGO0                            (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x06)
#define REG_PI_CODE_RGO1                            (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x07)
#define REG_PI_CODE_RGO2                            (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x08)
#define REG_PI_CH0_S2P_WPT_CTRL                     (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x10)
#define REG_PI_CH1_S2P_WPT_CTRL                     (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x11)
#define REG_PI_CH2_S2P_WPT_CTRL                     (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x12)
#define REG_PI_S2P_WPT0                             (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x13)
#define REG_PI_S2P_WPT1                             (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x14)
#define REG_PI_FIFO_RST                             (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x15)
#define REG_PI_CH0_SKEW_CTRL                        (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x16)
#define REG_PI_CH1_SKEW_CTRL                        (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x17)
#define REG_PI_CH2_SKEW_CTRL                        (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x18)
#define REG_PI_S2P_SKEW_CTRL                        (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x19)
#define REG_PI_SKEW_STS0                            (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x1a)
#define REG_PI_SKEW_STS1                            (MS7200_HDMI_RX_PI_RXRCV_REG_BASE + 0x1b)


#define MS7200_HDMI_RX_PI_RXPHY_REG_BASE            (0x1000)

#define REG_PI_RXPLL_CTRL0                          (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x00)
#define REG_PI_RXPLL_CTRL1                          (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x01)
#define REG_PI_RXPLL_CTRL2                          (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x02)
#define REG_PI_RXPLL_CTRL3                          (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x03)
#define REG_PI_RXPLL_CTRL4                          (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x04)
#define REG_PI_RXPLL_CTRL5                          (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x05)
#define REG_PI_RX_PLL_CFG_SEL                       (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x0f)
#define REG_PI_RX_PLL_CAL_TRIG                      (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x10)
#define REG_PI_RX_PLL_FREQM_CTRL                    (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x11)
#define REG_PI_RX_PLL_FREQ_RNG1                     (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x12)
#define REG_PI_RX_PLL_FREQ_RNG2                     (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x14)
#define REG_PI_RXPLL_STS                            (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x16)
#define REG_PI_CAL_REF_FREQ                         (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x17)
#define REG_PI_CAL_FREQ                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x19)
#define REG_PI_PLL_CAL_RESULT0                      (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x1b)
#define REG_PI_PLL_CAL_RESULT1                      (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x1c)
#define REG_PI_PLL_CAL_RESULT2                      (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x1d)
#define REG_PI_TMDS_FREQ                            (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x1e)
#define REG_RX_PI_CTRL1                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x20)
#define REG_RX_PI_CTRL2                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x21)
#define REG_RX_PI_CTRL3                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x22)
#define REG_RX_PI_CTRL4                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x23)
#define REG_RX_PI_CTRL5                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x24)
#define REG_PI_RX_TRM_CTRL                          (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x25)
#define REG_PI_RX_OFST_CTRL1                        (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x26)
#define REG_PI_RX_OFST_CTRL2                        (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x27)
#define REG_PI_RX_OFST_CTRL3                        (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x28)
#define REG_PI_RX_OFST_CTRL4                        (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x29)
#define REG_PI_RX_OFST_CTRL5                        (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x2a)
#define REG_PI_RX_GAIN_CTRL1                        (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x2b)
#define REG_PI_RX_GAIN_CTRL2                        (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x2c)
#define REG_PI_RX_CTRL0                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x2d)
#define REG_PI_RX_CTRL1                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x2e)
#define REG_PI_RX_CTRL2                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x2f)
#define REG_PI_RX_OVL_STS                           (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x30)
#define REG_PI_RX_CTRL3                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x31)
#define REG_PI_RX_CTRL4                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x32)
#define REG_PI_RX_CTRL5                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x33)
#define REG_PI_RX_CTRL6                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x34)
#define REG_PI_RX_CTRL7                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x35)
#define REG_PI_RX_CTRL8                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x36)
#define REG_PI_RX_CTRL9                             (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x37)
#define REG_PI_RX_CTRL10                            (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x38)
#define REG_PI_RX_CTRL11                            (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x39)
#define REG_PI_RX_EQ_SEL                            (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x3a)
#define REG_PI_RX_PHY_INTR                          (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x3b)



//20181218, for register program val check only.no effect.
#define REG_PI_RX_REGISTER_CHECK                    (MS7200_HDMI_RX_PI_RXPHY_REG_BASE + 0x100)
#define REG_PI_RX_REGISTER_CHECK_VAL                (0xAA)

/* end hdmi rx phy register map */


/* hdmi rx edid ram register address map */
#define MS7200_HDMI_RX_EDID_RAM_REGBASE             (0x0d00)

#define REG_EDID_BLOCK0                             (MS7200_HDMI_RX_EDID_RAM_REGBASE + 0x000)
#define REG_EDID_BLOCK1                             (MS7200_HDMI_RX_EDID_RAM_REGBASE + 0x080)
#define REG_EDID_BLOCK2                             (MS7200_HDMI_RX_EDID_RAM_REGBASE + 0x100)
#define REG_EDID_BLOCK3                             (MS7200_HDMI_RX_EDID_RAM_REGBASE + 0x180)
/* end hdmi rx edid ram register map */


/* hdmi rx controller register address map */
#define MS7200_HDMI_RX_CONTROLLER_REGBASE           (0x2000)

//id_hdmi                                           (0x2000)
#define REG_HDMI_SETUP_CTRL                         (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x000)
#define REG_HDMI_MODE_RECOVER                       (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x080)
#define REG_HDMI_SYNC_CTRL                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x090)
#define REG_HDMI_CKM_F                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x098)
#define REG_HDMI_CKM_EVLTM                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x094)
#define REG_HDMI_CKM_RESULT                         (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x09c)
#define REG_HDMI_DCM_CTRL                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0a8)
#define REG_HDMI_VM_CFG_CH_0_1                      (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0b0)
#define REG_HDMI_VM_CFG_CH_2                        (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0b4)
#define REG_HDMI_STS                                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0bc)
//id_hdcp_1_4                                       (0x20c0)
#define REG_HDCP_CTRL                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0c0)
#define REG_HDCP_SETTINGS                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0c4)
#define REG_HDCP_BKSV1                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0cc)
#define REG_HDCP_BKSV0                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0d0)
#define REG_HDCP_KEY1                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0d8)
#define REG_HDCP_KEY0                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0dc)
#define REG_HDCP_DBG                                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0e0)
#define REG_HDCP_EESS_WOO                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0f4)
#define REG_HDCP_STS                                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x0fc)
//id_mode_detection                                 (0x2140)
#define REG_MD_HCTRL1                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x140)
#define REG_MD_HCTRL2                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x144)
#define REG_MD_HT0                                  (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x148)
#define REG_MD_HT1                                  (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x14c)
#define REG_MD_HACT_PX                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x150)
#define REG_MD_VCTRL                                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x158)
#define REG_MD_VSC                                  (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x15c)
#define REG_MD_VOL                                  (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x164)
#define REG_MD_VAL                                  (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x168)
#define REG_MD_VTH                                  (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x16c)
#define REG_MD_VTL                                  (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x170)
#define REG_MD_IL_CTRL                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x174)
#define REG_MD_STS                                  (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x180)
#define REG_MD_HTIMING1                             (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x184)
#define REG_MD_HTIMING2                             (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x188)
#define REG_MD_VTIMING1                             (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x18c)
#define REG_MD_VTIMING2                             (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x190)
#define REG_MD_VTIMING3                             (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x194)
#define REG_MD_HTIMING1_LL                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x198)
#define REG_MD_HTIMING2_LL                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x19c)

//id_audio                                          (0x2200)
#define REG_AUD_FIFO_CTRL                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x240)
#define REG_AUD_FIFO_TH                             (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x244)
#define REG_AUD_FIFO_CLR_MM                         (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x24c)
#define REG_AUD_CHEXTR_CTRL                         (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x254)
#define REG_AUD_MUTE_CTRL                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x258)
#define REG_AUD_SAO_CTRL                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x260)
#define REG_AUD_SPARE                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x268)
#define REG_AUD_FIFO_STS                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x27c)
//id_packet_decoder                                 (0x2300)
#define REG_PDEC_CTRL                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x300)
#define REG_PDEC_FIFO_DATA                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x30c)
#define REG_PDEC_FIFO_STS1                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x324)
#define REG_PDEC_ACRM_CTRL                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x330)
#define REG_PDEC_ERR_FILTER                         (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x33c)
#define REG_PDEC_STS                                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x360)
#define REG_PDEC_AUD_STS                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x364)
#define REG_PDEC_VSI_PAYLOAD0                       (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x368)
#define REG_PDEC_GCP_AVMUTE                         (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x380)
#define REG_PDEC_ACR_CTS                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x390)
#define REG_PDEC_ACR_N                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x394)
#define REG_PDEC_AVI_HB                             (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x3a0)
#define REG_PDEC_AVI_PB                             (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x3a4)
#define REG_PDEC_AIF_PB0                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x3c8)
#define REG_PDEC_VSI_ST1                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x3e4)
//id_cea_video
#define MS7200_HDMI_RX_CEA_VIDEO_REG                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x400)
#define MS7200_HDMI_RX_CEAVID_CONFIG                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x400)
#define MS7200_HDMI_RX_CEAVID_3DCONFIG              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x404)
#define MS7200_HDMI_RX_CEAVID_HCOMFIG_LO            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x408)
#define MS7200_HDMI_RX_CEAVID_HCONFIG_HI            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x40c)
#define MS7200_HDMI_RX_CEAVID_VCONFIG_LO            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x410)
#define MS7200_HDMI_RX_CEAVID_VCONFIG_HI            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x414)
#define MS7200_HDMI_RX_CEAVID_STATUS                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x418)
//id_hdmi_2_0                                       (0x2800)
#define REG_HDMI20_CONTROL                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x800)
#define REG_SCDC_CONFIG                             (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x808)
#define REG_CHLOCK_CONFIG                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x80c)
#define REG_SCDC_REGS1                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x824)
#define REG_SCDC_REGS2                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x828)
//id_packet_decoder_interrupt                       (0xf78)
#define REG_PDEC_IEN_SET                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xf7c)
#define REG_PDEC_ISTS                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xf80)
#define REG_PDEC_ICLR                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xf88)
//id_audio_and_cec_interrupt                        
#define MS7200_HDMI_RX_AUDIO_AND_CEC_INTERRUPT_REG  (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xf90)
#define REG_AUD_CEC_IEN_SET                         (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xf94)
#define REG_AUD_CEC_ISTS                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xf98)
#define REG_AUD_CEC_IEN                             (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xf9c)
#define REG_AUD_CEC_ICLR                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfa0)
#define REG_AUD_CEC_ISET                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfa4)
//id_audio_fifo_interrupt
#define MS7200_HDMI_RX_AUDIO_FIFO_INTERRUPT_REG     (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfa8)
#define REG_AFIFO_IEN_SET                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfac)
#define REG_AFIFO_ISTS                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfb0)
#define REG_AFIFO_ICLR                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfb8)
//id_mode_detection_interrupt                       
#define REG_MD_IEN_SET                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfc4)
#define REG_MD_ISTS                                 (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfc8)
#define REG_MD_ICLR                                 (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfd0)
//id_hdmi_interrupt
#define MS7200_HDMI_RX_HDMI_INTERRUPT_REG           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfd8)
#define REG_HDMI_IEN_SET                            (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfdc)
#define REG_HDMI_ISTS                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfe0)
#define REG_HDMI_ICLR                               (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xfe8)
//id_dmi                                            (0x2ff0)
#define REG_SW_RST                                  (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xff0)
#define REG_DMI_DISABLE_IF                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0xff4)
//id_CEC                                            
#define REG_CEC_CTRL                                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f00)
#define REG_CEC_MASK                                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f08)
#define REG_CEC_ADDR_L                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f14)
#define REG_CEC_ADDR_H                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f18)
#define REG_CEC_TX_CNT                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f1c)
#define REG_CEC_RX_CNT                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f20)
#define REG_CEC_TX_DATA_0                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f40)
#define REG_CEC_TX_DATA_1                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f44)
#define REG_CEC_TX_DATA_2                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f48)
#define REG_CEC_TX_DATA_3                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f4c)
#define REG_CEC_TX_DATA_4                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f50)
#define REG_CEC_TX_DATA_5                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f54)
#define REG_CEC_TX_DATA_6                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f58)
#define REG_CEC_TX_DATA_7                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f5c)
#define REG_CEC_TX_DATA_8                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f60)
#define REG_CEC_TX_DATA_9                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f64)
#define REG_CEC_TX_DATA_10                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f68)
#define REG_CEC_TX_DATA_11                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f6c)
#define REG_CEC_TX_DATA_12                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f70)
#define REG_CEC_TX_DATA_13                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f74)
#define REG_CEC_TX_DATA_14                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f78)
#define REG_CEC_TX_DATA_15                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f7c)
#define REG_CEC_RX_DATA_0                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f80)
#define REG_CEC_RX_DATA_1                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f84)
#define REG_CEC_RX_DATA_2                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f88)
#define REG_CEC_RX_DATA_3                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f8c)
#define REG_CEC_RX_DATA_4                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f90)
#define REG_CEC_RX_DATA_5                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f94)
#define REG_CEC_RX_DATA_6                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f98)
#define REG_CEC_RX_DATA_7                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1f9c)
#define REG_CEC_RX_DATA_8                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1fa0)
#define REG_CEC_RX_DATA_9                           (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1fa4)
#define REG_CEC_RX_DATA_10                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1fa8)
#define REG_CEC_RX_DATA_11                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1fac)
#define REG_CEC_RX_DATA_12                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1fb0)
#define REG_CEC_RX_DATA_13                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1fb4)
#define REG_CEC_RX_DATA_14                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1fb8)
#define REG_CEC_RX_DATA_15                          (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1fbc)
#define REG_CEC_LOCK                                (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1fc0)
#define REG_WAKEUPCTRL                              (MS7200_HDMI_RX_CONTROLLER_REGBASE + 0x1fc4)
/* end hdmi rx controller module register map */



/* hdmi rx controller register address map */
#define MS7200_AUPLL_REGBASE                        (0x0400)

//Audio PLL                                          
#define REG_AUPLL_PWR                               (MS7200_AUPLL_REGBASE + 0x000)
#define REG_AUPLL_M                                 (MS7200_AUPLL_REGBASE + 0x001)
#define REG_AUPLL_FN_L                              (MS7200_AUPLL_REGBASE + 0x002)
#define REG_AUPLL_FN_M                              (MS7200_AUPLL_REGBASE + 0x003)
#define REG_AUPLL_FN_H                              (MS7200_AUPLL_REGBASE + 0x004)
#define REG_AUPLL_CTRL1                             (MS7200_AUPLL_REGBASE + 0x005)
#define REG_AUPLL_CTRL2                             (MS7200_AUPLL_REGBASE + 0x006)
#define REG_AUPLL_POS_DVI                           (MS7200_AUPLL_REGBASE + 0x007)
#define REG_AUPLL_TEST_CTRL                         (MS7200_AUPLL_REGBASE + 0x008)
#define REG_AUPLL_CFG_CTRL                          (MS7200_AUPLL_REGBASE + 0x009)
#define REG_AUPLL_CFG_COEF                          (MS7200_AUPLL_REGBASE + 0x00A)
#define REG_AUPLL_UPD_TIMER_L                       (MS7200_AUPLL_REGBASE + 0x00B)
#define REG_AUPLL_UPD_TIMER_M                       (MS7200_AUPLL_REGBASE + 0x00C)
#define REG_AUPLL_UPD_TIMER_H                       (MS7200_AUPLL_REGBASE + 0x00D)
#define REG_AUPLL_FIFO_TH1_L                        (MS7200_AUPLL_REGBASE + 0x00E)
#define REG_AUPLL_FIFO_TH1_H                        (MS7200_AUPLL_REGBASE + 0x00F)
#define REG_AUPLL_FIFO_TH2_L                        (MS7200_AUPLL_REGBASE + 0x010)
#define REG_AUPLL_FIFO_TH2_H                        (MS7200_AUPLL_REGBASE + 0x011)
#define REG_AUPLL_FIFO_TH3_L                        (MS7200_AUPLL_REGBASE + 0x012)
#define REG_AUPLL_FIFO_TH3_H                        (MS7200_AUPLL_REGBASE + 0x013)
#define REG_AUPLL_FIFO_TH4_L                        (MS7200_AUPLL_REGBASE + 0x014)
#define REG_AUPLL_FIFO_TH4_H                        (MS7200_AUPLL_REGBASE + 0x015)
#define REG_AUPLL_FIFO_TH5_L                        (MS7200_AUPLL_REGBASE + 0x016)
#define REG_AUPLL_FIFO_TH5_H                        (MS7200_AUPLL_REGBASE + 0x017)
#define REG_AUPLL_FIFO_TH6_L                        (MS7200_AUPLL_REGBASE + 0x018)
#define REG_AUPLL_FIFO_TH6_H                        (MS7200_AUPLL_REGBASE + 0x019)
#define REG_AUPLL_FIFO_TH7_L                        (MS7200_AUPLL_REGBASE + 0x01A)
#define REG_AUPLL_FIFO_TH7_H                        (MS7200_AUPLL_REGBASE + 0x01B)
#define REG_AUPLL_FREQ_INC_STEP4                    (MS7200_AUPLL_REGBASE + 0x01C)
#define REG_AUPLL_FREQ_INC_STEP3                    (MS7200_AUPLL_REGBASE + 0x01D)
#define REG_AUPLL_FREQ_INC_STEP2                    (MS7200_AUPLL_REGBASE + 0x01E)
#define REG_AUPLL_FREQ_INC_STEP1                    (MS7200_AUPLL_REGBASE + 0x01F)
#define REG_AUPLL_FREQ_DEC_STEP1                    (MS7200_AUPLL_REGBASE + 0x020)
#define REG_AUPLL_FREQ_DEC_STEP2                    (MS7200_AUPLL_REGBASE + 0x021)
#define REG_AUPLL_FREQ_DEC_STEP3                    (MS7200_AUPLL_REGBASE + 0x022)
#define REG_AUPLL_FREQ_DEC_STEP4                    (MS7200_AUPLL_REGBASE + 0x023)
#define REG_AUPLL_M_VAL                             (MS7200_AUPLL_REGBASE + 0x024)
#define REG_AUPLL_FN_VAL_L                          (MS7200_AUPLL_REGBASE + 0x025)
#define REG_AUPLL_FN_VAL_M                          (MS7200_AUPLL_REGBASE + 0x026)
#define REG_AUPLL_FN_VAL_H                          (MS7200_AUPLL_REGBASE + 0x027)
#define REG_AUPLL_LOCK                              (MS7200_AUPLL_REGBASE + 0x028)
#define REG_AUPLL_FREQ_RANGE                        (MS7200_AUPLL_REGBASE + 0x029)
#define REG_AUPLL_FIFO_DIFF_TH                      (MS7200_AUPLL_REGBASE + 0x02A)




#endif // __MACROSILICON_MS7200_DRV_HDMI_RX_CONFIG_H__
