#ifndef GSV5K1_SEC_MAP_FCT_H
#define GSV5K1_SEC_MAP_FCT_H
#define GSV5K1_SEC_set_VP_MODE(port, val)                             AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x01, 0x70, 4, val)
#define GSV5K1_SEC_get_CP_CSC_BYPASS(port, pval)                      AvHalI2cReadField8(GSV5K1_SEC_MAP_ADDR(port), 0x01, 0x8, 0x3, pval)
#define GSV5K1_SEC_set_CP_CSC_BYPASS(port, val)                       AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x01, 0x8, 0x3, val)
#define GSV5K1_SEC_get_CP_MODE(port, pval)                            AvHalI2cReadField8(GSV5K1_SEC_MAP_ADDR(port), 0x01, 0x7, 0, pval)
#define GSV5K1_SEC_set_CP_MODE(port, val)                             AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x01, 0x7, 0, val)
#define GSV5K1_SEC_set_VP_MODE_MAN_EN(port, val)                      AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x02, 0x80, 0x7, val)
#define GSV5K1_SEC_get_TX2_DSC_EN(port, pval)                         AvHalI2cReadField8(GSV5K1_SEC_MAP_ADDR(port), 0x03, 0x80, 0x7, pval)
#define GSV5K1_SEC_set_TX2_DSC_EN(port, val)                          AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x03, 0x80, 0x7, val)
#define GSV5K1_SEC_get_TX1_DSC_EN(port, pval)                         AvHalI2cReadField8(GSV5K1_SEC_MAP_ADDR(port), 0x03, 0x40, 0x6, pval)
#define GSV5K1_SEC_set_TX1_DSC_EN(port, val)                          AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x03, 0x40, 0x6, val)
#define GSV5K1_SEC_get_DSC_COM_RATIO(port, pval)                      AvHalI2cReadField8(GSV5K1_SEC_MAP_ADDR(port), 0x03, 0xC, 2, pval)
#define GSV5K1_SEC_set_DSC_COM_RATIO(port, val)                       AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x03, 0xC, 2, val)
#define GSV5K1_SEC_get_DSC_H_DIV2_EN(port, pval)                      AvHalI2cReadField8(GSV5K1_SEC_MAP_ADDR(port), 0x03, 0x2, 0x1, pval)
#define GSV5K1_SEC_set_DSC_H_DIV2_EN(port, val)                       AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x03, 0x2, 0x1, val)
#define GSV5K1_SEC_set_VP_SRC_SEL(port, val)                          AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x04, 0x30, 4, val)
#define GSV5K1_SEC_set_CP_SRC_SEL(port, val)                          AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x04, 0x3, 0, val)
#define GSV5K1_SEC_set_TX2_SRC_SEL(port, val)                         AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x05, 0x38, 3, val)
#define GSV5K1_SEC_set_TX1_SRC_SEL(port, val)                         AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0x05, 0x7, 0, val)
#define GSV5K1_SEC_set_RXB_FIFO_EN(port, val)                         AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0xCE, 0x20, 0x5, val)
#define GSV5K1_SEC_set_RXA_FIFO_EN(port, val)                         AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0xCE, 0x10, 0x4, val)
#define GSV5K1_SEC_set_RXB_FIFO_EN_OVERRIDE(port, val)                AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0xCE, 0x2, 0x1, val)
#define GSV5K1_SEC_set_RXA_FIFO_EN_OVERRIDE(port, val)                AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0xCE, 0x1, 0x0, val)
#define GSV5K1_SEC_set_CCA_TX_RST(port, val)                          AvHalI2cWriteField8(GSV5K1_SEC_MAP_ADDR(port), 0xEC, 0x80, 0x7, val)
#endif
